### ISSUE TITLE
Immutable.List(...).traverse is not a function

### ISSUE THREAD

**Issue by chrisui** [salesforce-ux/theo#127] opened 2017-11-02 18:42 UTC
Raised an issue over in `gulp-theo` but wanted to post here as this repo seems a little better monitored.

After installing the most recent version of `gulp-theo` we receive the following error when running the defined task:

```
(node:57669) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): TypeError in plugin 'gulp-theo'
Message:
    Immutable.List(...).traverse is not a function
```

Issue on gulp-theo: https://github.com/salesforce-ux/gulp-theo/issues/2

**Comment by chrisui** [comment] 2017-11-02 18:49
Interestingly I can't find any traces of the referenced `List.traverse` method in the latest Immutable docs. Is this a versioning issue? 

https://facebook.github.io/immutable-js/docs/#/List

**Comment by chrisui** [comment] 2017-11-02 18:50
$ ls immutable
@kalo/ui@0.6.2 /Users/chris/Projects/project
└─┬ gulp-theo@1.0.0-alpha.5
  └── immutable@3.8.2

**Comment by aputinski** [comment] 2017-11-02 20:52
I think I see the problem. We're using `immutable-ext` which ironically mutates `immutable` with some additional methods. Because we're using a different version of `immutable` on `gulp-theo` for the options, it never gets those extra methods. I'll release a new version of `gulp-theo` that removes that dependency all together.

**Comment by aputinski** [comment] 2017-11-02 21:49
I just published `gulp-theo@1.0.0-beta.1` Please let me know if a fresh install fixes the issue.

**Comment by chrisui** [comment] 2017-11-06 20:07
This seems to have resolved the issue. Thanks @aputinski for the quick fix!

**Comment by chrisui** [comment] 2017-11-06 20:24
Think I jumped the gun a little. Turns out no files were piped to the plugin so ofc the step was passing (oops). It's failing on the following stub file with same error as before:

```
global:
  type: color
  category: colors
props:
  pink300:
    value: '#FBDFE2'
```

**Comment by chrisui** [comment] 2017-11-21 11:12
@aputinski Any chance of a quick look on this?

**Comment by aputinski** [comment] 2017-11-21 16:13
Hm.. I'm gonna need a little more info. I did a fresh install and the example you pasted above seems to run with no problems. What node/npm version are you running?

**Comment by chrisui** [comment] 2017-11-21 16:19
| Executable | Version |
| ---: | :--- |
| `lerna --version` | 2.5.1 |
| `npm --version`  | 3.10.8 |
| `yarn --version` | 1.3.2 |
| `node --version` | v6.9.1 |

| OS | Version |
| --- | --- |
| NAME | VERSION |
| macOS Sierra | 10.12.6 |

Will try to get a repro!

**Comment by MindSculpt** [comment] 2017-12-08 18:25
I'm seeing this same issue after your update. Fresh install did not fix it.

**Comment by aputinski** [comment] 2017-12-08 19:09
Ok, I think I found the issue. Can you try `6.0.0-beta.9`?

**Comment by MindSculpt** [comment] 2017-12-08 19:25
@aputinski Looks like that fixed it. Nice work, and thanks!

**Comment by aputinski** [comment] 2017-12-08 19:29
@chrisui I'm gonna close this for now, but feel free to re-open if `6.0.0-beta.9` doesn't fix the issue

**Closed by aputinski** 2017-12-08 19:29 UTC

**Comment by chrisui** [comment] 2017-12-12 10:45
@aputinski Will take it for a spin. If you don't hear from me again it's worked and THANK YOU! :)

**Comment by MindSculpt** [comment] 2018-03-12 18:16
Looks like this might be back when I upgrade to the newest versions of `gulp-theo` and `theo`. The only information I'm getting on error is: `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]`

Nothing has changed on my end other than updating these package versions. Any ideas?

**Comment by aputinski** [comment] 2018-03-13 12:55
What versions of each are you using?

**Comment by MindSculpt** [comment] 2018-03-15 18:49
I'm currently using `gulp-theo 1.0.0-beta.1`. I have theo as a dev dependency but it's actually not being used right now, so the issue is with just the upgrade.

**Comment by siiron** [comment] 2018-03-19 21:26
Same here. I just ran a clean install of `gulp-theo 1.0.0` and I'm getting the same error `UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): [object Object]`.
